hash = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
modulus_limbs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
redc_limbs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
signature_limbs = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
